name = "dt"
license = "MIT"
licenselink = ".../blob/master/LICENSE"
description = "From blank Starter Hugo theme for developers."
homepage = "https://github.com/vimux/blank/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Vimux"
  homepage = "https://github.com/vimux"
