baseURL = "/"
languageCode = "fr-ch"
title = "Dre Dorota Teterycz  – Médecine Esthétique"
theme = "dt"
description = "Je m'appelle Dorota Teterycz. J'ai fondé ce cabinet de médecine esthétique pour pratiquer des interventions médicales dans un but esthétique, sans opération."


[markup]
  [markup.goldmark]
	[markup.goldmark.renderer]
	  unsafe = true

[menu]
  [[menu.main]]
		identifier = "accueil"
		name = "Accueil"
		url = "/"
		weight = 1 

  [[menu.main]]
		identifier = "dre-dorota-teterycz"
		name = "Dre Dorota Teterycz"
		url = "/dre-dorota-teterycz/"
		weight = 2 

	[[menu.main]]
		identifier = "objectifs"
		name = "Vos objectifs"
		url = "/objectifs/"
		weight = 3

  [[menu.main]]
		identifier = "prestations"
		name = "Mes prestations"
		url = "/prestations/"
		weight = 3

  [[menu.main]]
		identifier = "rendez-vous"
		name = "Contact"
		url = "/rendez-vous/"
		weight = 5


